import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/footer";
import NavbarSkeleton from "@/components/NavbarSkeleton";
import { Suspense } from "react";
import FooterSkeleton from "@/components/FooterSkeleton";
import ScrollToTop from "@/components/ScrollToTop";
import { getInvestorNavbarData } from "@/lib/investorNavbarQuery";
import { PageHeader } from "@/components/Page-Header";

const poppins = Poppins({
  subsets: ["latin"],
  variable: '--font-poppins', // Assign CSS variable
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "J. Kumar",
  description: "Generated by create next app",
};

export const revalidate = 0;


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const investorData = await getInvestorNavbarData(); // prisma runs here

  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body
        className="antialiased bg-background font-(family-name:--font-poppins)"
      >
        <ScrollToTop/>
        <Suspense fallback={<NavbarSkeleton />}>
          <Navbar categories={investorData} />
        </Suspense>
        <PageHeader/>
        <main>
        {children}
        </main>
        <Suspense fallback={<FooterSkeleton />}>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
